### API CONSULTA - GET por médico

GET http://localhost:8080/api/v1/consulta/medico/1
Accept: application/json

###

### API CONSULTA - GET por paciente

GET http://localhost:8080/api/v1/consulta/paciente/1
Accept: application/json

###

### API CONSULTA - POST (agendar nova consulta)

POST http://localhost:8080/api/v1/consulta
Content-Type: application/json

{
    "status": "Agendada",
    "paciente": 
  {
    "id": 1,
    "nome": "Leandro Bittencourt",
    "cpf": "069.208.329-41",
    "dataNascimento": "2005-07-16",
    "telefone": "(47) 99654-9945",
    "email": "leandro.balansin2005@gmail.com",
    "convenio": "Unimed",
    "endereco": "rua prefeito helmuth fallgatter 785",
    "historicoMedico": null,
    "senha": null
  },

    "medico": {
    "id": 1,
    "nome": "Claudecir Evandro Gambeta",
    "especialidade": "Joelho",
    "agenda": null,
    "pacientes": null,
    "crm": "11114-SC",
    "senha": null
  },
    
}
