### API MÉDICO - GET

GET http://localhost:8080/api/medico
Accept: application/json

###

### API MÉDICO - POST

POST http://localhost:8080/api/medico
Content-Type: application/json

{
    "id": 0,
    "nome": "Claudecir Evandro Gambeta",
    "especialidade": "Joelho",
    "crm": "11114-SC"
}

###

### API MÉDICO - PUT

PUT http://localhost:8080/api/medico/1
Content-Type: application/json

{
    "id": 1,
    "nome": "Claudecir Evandro Gambeta",
    "especialidade": "Joelho",
    "crm": "11114-SC"
}

###

### API MÉDICO - DELETE

DELETE http://localhost:8080/api/medico/1
Content-Type: application/json
